/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as TonconnectManifestDotjsonRouteImport } from './routes/tonconnect-manifest[.]json'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api/telegram/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const TonconnectManifestDotjsonRoute =
  TonconnectManifestDotjsonRouteImport.update({
    id: '/tonconnect-manifest.json',
    path: '/tonconnect-manifest.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/api/telegram/webhook',
  path: '/api/telegram/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/tonconnect-manifest.json': typeof TonconnectManifestDotjsonRoute
  '/api/health': typeof ApiHealthRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/tonconnect-manifest.json': typeof TonconnectManifestDotjsonRoute
  '/api/health': typeof ApiHealthRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/tonconnect-manifest.json': typeof TonconnectManifestDotjsonRoute
  '/api/health': typeof ApiHealthRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/tonconnect-manifest.json'
    | '/api/health'
    | '/api/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/tonconnect-manifest.json'
    | '/api/health'
    | '/api/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/tonconnect-manifest.json'
    | '/api/health'
    | '/api/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  TonconnectManifestDotjsonRoute: typeof TonconnectManifestDotjsonRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiTelegramWebhookRoute: typeof ApiTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tonconnect-manifest.json': {
      id: '/tonconnect-manifest.json'
      path: '/tonconnect-manifest.json'
      fullPath: '/tonconnect-manifest.json'
      preLoaderRoute: typeof TonconnectManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/webhook': {
      id: '/api/telegram/webhook'
      path: '/api/telegram/webhook'
      fullPath: '/api/telegram/webhook'
      preLoaderRoute: typeof ApiTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  TonconnectManifestDotjsonRoute: TonconnectManifestDotjsonRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
